### PR TITLE
new git scripts

### PR DESCRIPTION
**Pull request by jindraj**
Scripts:
 * ./git/convert.sh #TODO DELETE
 * ./git/get_summary.sh
 * ./git/generate.sh

The output filenames suffix *_new* will be dropped before merging to replace all the files.
File neomutt_new.txt is sorted and can be diffed between revisions.

1. ./git/convert.sh
Need to be run as first to create email address files in format that scripts *contributors.sh* and *generate.sh* understand
```sh
  ./git/convert.sh neomutt.txt neomutt > a && mv a neomutt_new.txt
```
```sh
  ./git/convert.sh mutt.txt mutt > a && mv a mutt_new.txt
```

2. ./git/get_summary.sh
```sh
./git/contributors.sh PATH_TO_NEOMUTT_REPO from_ref to_ref
```
 * Reads commits of NEOMUTT_REPO since from_ref (or last release if omitted) until to_ref (or current HEAD if omitted).
 * New contributors are added to e-mail address list file (neomutt_new.txt),
 * the same applies for new e-mail addresses of regular contributors.
 * Prints text "Many thanks to our new contributors… and our regular contributors…"
 * when run with DEBUG env variable set (to any value) some info about progress

 3. ./git/generate.sh
  * replacement for *mailmap.sh* *mailmap-nick.sh* *mailmap-name-nick.sh* and *credits.sh*
  * creates files *mailmap_new*, *mailmap-nick_new*, *mailmap-name-nick_new* and *credits_new*

### CODE REVIEW

**Comment by flatcap** [comment]
Bug:
- `generate.sh` is creating mixed mailmap entries, e.g.
  `Aleksa Sarai <cyphar@>  Darshit Shah <darnir@>`

To do:
- `contributors.sh` output in `First Last (@nick)` form
- sort lists in `LANG=C` locale for consistency
- mailmaps: add comments: `## NeoMutt contributors`,  `## Mutt contributors`
- De-dupe `neomutt_new.txt`
- sort `neomutt_new.txt`

**Comment by jindraj** [comment]
> Bug:
> 
> * `generate.sh` is creating mixed mailmap entries, e.g.
>   `Aleksa Sarai <cyphar@>  Darshit Shah <darnir@>`
> 
I believe this was because neomutt_new.txt wasn't sorted properly. After sorting neomutt_new.txt I wasn't able to reproduce.

> To do:
> 
> * `contributors.sh` output in `First Last (@nick)` form
✅
> * sort lists in `LANG=C` locale for consistency
✅
> * mailmaps: add comments: `## NeoMutt contributors`,  `## Mutt contributors`
✅
> * De-dupe `neomutt_new.txt`
✅manually
> * sort `neomutt_new.txt`
✅

**Comment by flatcap** [comment]
I've removed a bunch more dupes and I've found 39 missing entries.

You can see them if you `./generate.sh`, then edit the `mailmap` to prefix each line with `KNOWN `.
Then in the `neomutt` repo, run `git shortlog --summary | grep -v KNOWN`

It's caused by a difference between the commit name and the preferred name, e.g.
Original:
```
Eric Raymond    esr@thyrsus.com
        Unknown <esr@thyrsus.com>
```

New:
```
mutt,,esr@thyrsus.com,Eric Raymond,preferred
```

The new one doesn't match the commit, which had a name of `Unknown`.

Also, `generate.sh` should filter out people without an email address.

**Comment by jindraj** [comment]
I'll think about how to add them back and preserve them. I added checking combination of mail+name to `getcontribs()` in *contributors.sh* which decides whether to add or not a new record to known contributors.

I'm starting to be a little sceptical if changing the e-mail address list file was a bright idea. But automatically adding records to previos format would be more painful I guess.

**Comment by jindraj** [comment]
ouch… that means that I need to record every email address as it appeared. Even with nbsp which I just replaced with normal space…
Because I'm one of the missing addresses and hexdump

>00000000: 3c6a 616b 7562 2e6a 696e 6472 6140 736f  <jakub.jindra@so
00000010: 6369 616c 6261 6b65 7273 2e63 6f6d 3e20  cialbakers.com>
00000020: 4a61 6b75 62**c2 a0**4a 696e 6472 61         Jakub..Jindra

… and mystery revealed. I have the nbsp in my .gitconfig 🤦‍♂️

**Comment by jindraj** [comment]
> Original:
> 
> ```
> Eric Raymond    esr@thyrsus.com
>         Unknown <esr@thyrsus.com>
> ```
> 
> New:
> 
> ```
> mutt,,esr@thyrsus.com,Eric Raymond,preferred
> ```

So having a little different format:
```
mutt,,preferred@example.com,preferred@example.com,Eric Raymond,preferred
mutt,,preferred@example.com,secondary@example.com,Unkown,secondary
```

where **3rd + 4th + 5th column** would be "PK" would be probably better…

**Comment by flatcap** [comment]
They're looking good.
Please can you:
- Drop the `new` prefixes
- Get rid of the old results files
- Update the README.md to explain what each script does

Ideas:
- The mailmap and credits are sorted by first name.
  Should the 'database' be sorted the same way?
  (i.e. rearrange the fields: Pretty name, pretty email, commit name, commit email, github name)

- The mailmap isn't for humans to read.
  Should we drop the formatting?
  Forget `column` and just space-delimit all the fields.
  (this would make comparisons simpler)

- The mailmap is auto-generated.
  I think we should add a comment, linking back to this repo, e.g.
  `# NeoMutt Contributors - auto-generated: https://github.com/neomutt/management/tree/master/git`

**Comment by jindraj** [comment]
> Ideas:
> 
> * The mailmap and credits are sorted by first name.
>   Should the 'database' be sorted the same way?
>   (i.e. rearrange the fields: Pretty name, pretty email, commit name, commit email, github name)

It makes sense to me to have it sorted by the **PK** `gh_username,preffered_email,email`,
rearranging fields is possible, it would need to be changed on multiple places.
In the case someone wants to change his preferred contact it's easier to do so than compared to when it's sorted by first name. But yes, we can. 

> * The mailmap isn't for humans to read.
x>   Forget `column` and just space-delimit all the fields.
>   (this would make comparisons simpler)

Makes sense ✅

> * The mailmap is auto-generated.
>   I think we should add a comment, linking back to this repo, e.g.
>   `# NeoMutt Contributors - auto-generated: https://github.com/neomutt/management/tree/master/git`

Good idea ✅

**Comment by jindraj** [comment]
I would like to make gen_summary.sh prepare all the things below:
- what we can see at [github releases](https://github.com/neomutt/neomutt/releases/tag/20200320)  template  [release-templates/github.md](https://github.com/neomutt/management/blob/master/release-templates/github.md)  – I guess releasing here triggers also e-mail notification to _neomutt/neomutt <neomutt.neomutt.github.com>_ maillist,
- and [news on website](https://neomutt.org/2020/03/20/release) template [release-templates/website.md](https://github.com/neomutt/management/blob/master/release-templates/website.md)

Also maillists:
- [devel](https://github.com/neomutt/management/blob/master/release-templates/dev-ml.txt),
- [users](https://github.com/neomutt/management/blob/master/release-templates/user-ml.txt).

Welcome new contribs [template](https://github.com/neomutt/management/blob/master/release-templates/newbies.txt) - we can create even more personalised since we know new contributors by name or nickname.

All of these look very similar or the same, shouldn't be hard to do so.

**Pull request merged**
